### PR TITLE
Update ember-cli-build-config-editor to v0.4.0

### PR DESCRIPTION
**Pull request by srvance**
Handles simple non-inline configuration declarations. Improved solution for #279.

I don't know how to write a test for this in ember-bootstrap, but there are tests in srvance/ember-cli-build-config-editor#9.

### CODE REVIEW

**Comment by srvance** [comment]
There was a weird transient failure in the ember-2.7 scenario that went away when I restarted. Unrelated to the PR. Have you seen that before?

**Comment by simonihmig** [comment]
Nice to have this!

> Have you seen that before?

No, but sometimes I have seen flacky tests with Travis...

One thing: the `yarn.lock` needs to be updated for this change to take effect for our own tests!

**Comment by srvance** [comment]
Wow! That hasn't been updated in awhile for ember-cli-build-config-editor. Done.

Also, are you seeing the "unmet peer dependency" warnings for `typescript` and `tslint` now?

**Comment by simonihmig** [comment]
> Also, are you seeing the "unmet peer dependency" warnings for typescript and tslint now?

I recall having seen that when upgrading an app to ember-cli 2.12 I think...

**Pull request merged**
