### PR TITLE
Trigger submit on all forms in modal body

### PR DESCRIPTION
**Pull request by Moxide**
See #362

### CODE REVIEW

**Comment by Moxide** [comment]
Ok in Chrome.
But in Firefox, the form is submitted and right after, a full page reload is triggered.

**Comment by Moxide** [comment]
Forget the last comment about Firefox, this only occured in my particular setup ;-)

**Comment by Moxide** [comment]
Done ;-)

**Comment by simonihmig** [comment]
Thanks @Moxide for working on this!

**Pull request merged**
