### PR TITLE
upgrade ember-cli-htmlbars to v5.6.0

### PR DESCRIPTION
**Pull request by jelhan**
This should fix the _unable to locate global object_ bug in Ember canary. https://github.com/kaliber5/ember-bootstrap/issues/1440#issuecomment-786674780

### CODE REVIEW

**Comment by jelhan** [comment]
Seems to cause an issue with `@embroider/macros`:

```
 - broccoliBuilderErrorStack: Error: /home/runner/work/ember-bootstrap/ember-bootstrap/ember-bootstrap/components/bs-accordion.js: argument to macroCondition must be statically analyzable
    at macroIfExpression (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/@embroider/macros/src/glimmer/macro-condition.js:43:15)
    at Object.macroIfMustache (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/@embroider/macros/src/glimmer/macro-condition.js:54:18)
    at MustacheStatement (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/@embroider/macros/src/glimmer/ast-transform.js:155:50)
    at visitNode (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7718:16)
    at visitArray (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7809:20)
    at visitKey (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7786:7)
    at visitNode (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7740:9)
    at visitKey (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7789:20)
    at visitNode (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7740:9)
    at visitArray (/home/runner/work/ember-bootstrap/ember-bootstrap/node_modules/ember-source/dist/ember-template-compiler.js:7809:20)
```

This is the only usage of `macroCondition` in `bs-accordion` template: https://github.com/kaliber5/ember-bootstrap/blob/806c40e67887ce12df76f06419eec2145c020395/addon/components/bs-accordion.hbs#L2

Seems to be a regression in ember-cli-htmlbars to me.

//cc @rwjblue

**Comment by simonihmig** [comment]
> Seems to be a regression in ember-cli-htmlbars to me.

Confirm. Already looked into it: https://github.com/embroider-build/embroider/issues/701

**Comment by simonihmig** [comment]
@jelhan can you pease update this to use at least `^5.6.2`, which fixes the embroider issue: https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.2

**Comment by jelhan** [comment]
Will do as soon as possible but currently away from keyboard. Feel free to push to my feature branch.

**Review by rwjblue — APPROVED** [review]

**Comment by jelhan** [comment]
Hard to tell if updating ember-cli-htmlbars fixes some of the issues in CI as so many other things are started to fail in parallel. Especially due to the deprecations. Maybe we can relax our deprecation assertions for now to have fewer things to care about in parallel @simonihmig.

**Review by simonihmig — APPROVED** [review]

**Comment by simonihmig** [comment]
> Hard to tell if updating ember-cli-htmlbars fixes some of the issues in CI as so many other things are started to fail in parallel.

I hope I can work on these on Friday!

**Pull request merged**
