### PR TITLE
Modal header components

### PR DESCRIPTION
**Pull request by simonihmig**
Allows for easier customization.

### CODE REVIEW

**Comment by simonihmig** [comment]
@srvance I guess that needs another manual merge into `bs4`... is this looking ok to you, regarding BS4 integration?

**Comment by srvance** [comment]
I had to move the close button after the title for the bs4 version of the header. If we can do that for both bs3 and bs4, it will simplify things. Keep this in mind as you merge. Otherwise, this looks good.

**Comment by srvance** [comment]
Oh, and there's also a change of the title tag from an `h4` to an `h5`.

**Comment by simonihmig** [comment]
Ok, thanks. should be no problem then...

**Pull request merged**
