### PR TITLE
Convert BsForm to Glimmer component

### LINKED ISSUE #1338: Tests for validation support in <BsForm> do not test validation plugin interface
The tests for validation support in `<BsForm>` and `<BsForm::Element>` rely on private properties. They don't test the interface for validation plugins but set arguments from outside.

Let's take this test as an example: https://github.com/kaliber5/ember-bootstrap/blob/50937097944ad7c8a0504088628fc1972606bea4/tests/integration/components/bs-form-test.js#L138-L170

It sets the properties `hasValidator` and `validate` by setting `@hasValidator` and `@validate` arguments. This is only working due to characteristics of `@ember/component`.

This does not tests validation provided by plugins as they exist. Both ember-bootstrap-changeset-validations and ember-bootstrap-cp-validations add validation support by subclassing `<BsForm::Element>`. This interface should be used in the tests as well.

### PR DESCRIPTION
**Pull request by simonihmig**
Also fixes tests to test real validation plugin interface, closes #1338

### CODE REVIEW

**Comment by simonihmig** [comment]
@jelhan we might need to update `ember-bootstrap-cp-validations` and `ember-bootstrap-changeset-validations` after landing this I guess? For them it might be a breaking change, while users should not be affected as they are not allowed to subclass components. But as we consider them "privileged" addons, we won't bump a major here, I think we agreed on that, right?

**Comment by simonihmig** [comment]
OK, due to the use of a component class (vs. component definition as with the `{{component}}` helper) tests are failing for older Ember. But I think I know how to fix. Also need to look into Embroider, but not today anymore...

**Comment by simonihmig** [comment]
I tested the changes locally with `ember-bootstrap-cp-validations`, and everything seems to work fine. `ember-bootstrap-changeset-validations` however fails. It is still using the legacy object model: https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/addon/components/bs-form.js#L6 🙁

So until that is fixed, I'll keep this open...

**Comment by jelhan** [comment]
> I tested the changes locally with `ember-bootstrap-cp-validations`, and everything seems to work fine. `ember-bootstrap-changeset-validations` however fails. It is still using the legacy object model: https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/addon/components/bs-form.js#L6 slightly_frowning_face
> 
> So until that is fixed, I'll keep this open...

Good catch. I created an issue in that repository to track: https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/39 Sadly I don't have time to pick it up right now.

**Comment by simonihmig** [comment]
I'll merge this now, as the fix on the `ember-bootstrap-changeset-validations` side has been merged as well. Will then cut a release for both addons soon...

**Pull request merged**
