### PR TITLE
Provide required & disabled functionality

### PR DESCRIPTION
**Pull request by offirgolan**
I also updated the dev dependencies since tests werent running on my local machine. :smile:

### CODE REVIEW

**Comment by simonihmig** [comment]
Did the same yesterday already, but did not push yet... :(

Does this include all of #67? So those PRs are mutually exclusive? Did not have time to check in detail...

**Comment by offirgolan** [comment]
It doesnt but I can add it super quick

**Comment by offirgolan** [comment]
@simonihmig added disabled functionality. Please give credit to @oswaldoacauan for that.

**Comment by oswaldoacauan** [comment]
I will close my PR. Good work @offirgolan :clap:

**Comment by simonihmig** [comment]
@offirgolan regarding my last question: just had a quick glance at it and did not realize the 2 PRs were about two different things (disabled & required), sorry about the confusion! Great that you could merge both into one nevertheless, would have caused merge conflicts everywhere otherwise...

@offirgolan & @oswaldoacauan: thanks for your combined effort, credits will go to both of you of course! :)

**Comment by offirgolan** [comment]
No worries at all! It was probably faster doing them both together than spending the time to merge 15 files :smile_cat:

**Pull request merged**
