### PR TITLE
Apply default values even if undefined is passed, allowing for easy wrapping of components

### PR DESCRIPTION
**Pull request by simonihmig**
As discussed in https://github.com/kaliber5/ember-bootstrap/pull/1282#discussion_r502948017, we remove the optional feature introduced in #1248 again, and make its behavior the default one.

### CODE REVIEW

**Comment by simonihmig** [comment]
Only failing for Canary, which should be fixed by #1284

**Review by jelhan — APPROVED** [review]

**Comment by jelhan** [comment]
I think this should be mentioned in the API docs. Not that sure about the title so. Technically it's about removing the optional feature. But from a consumer point of view it's about supporting passing arguments through without needing to worry about default values. I guess for better changelog the title should focus on that one.

**Comment by simonihmig** [comment]
Changed the title. Feel free to change again if you have something better, at least until it's release time again! :wink:

**Comment by simonihmig** [comment]
Just reverted that, and added the title and label to *your* PR, so you are correctly credited for that change! 😆

**Pull request merged**
