### PR TITLE
Improve yielded components

### PR DESCRIPTION
**Pull request by lougreenwood**
Follows on from #685

This PR allows overriding the remaining `ember-bootstrap` components.

This allows a user to extend any `ember-bootstrap` component and override the default `bs-*` components yielded out with their own extended implementations.

This PR omits work on `bs-modal-simple`.

A side effect of this PR is that `ember-bootstrap` should now "theoretically" be compatible with the upcoming MU structure where file-system nested components are not allowed :)

### CODE REVIEW

**Comment by simonihmig** [comment]
Thank you! I'll merge a bit later, wanted to figure something different out before...

> A side effect of this PR is that ember-bootstrap should now "theoretically" be compatible with the upcoming MU structure where file-system nested components are not allowed :)

What makes you think that? Or better, what makes you think that the current version does not support MU? 

I have been using this addon in a MU app, and works fine so far (except for #648): I think there *could* be an issue with MU if you directly accessed nested components. But here you only directly use root-level components, all the nested ones are yielded (like "private" components, which are supported by MU). Also not sure if that is true when you use the fallback resolver, which is needed AFAIK to support "classic" addons...

**Comment by lougreenwood** [comment]
I suppose you're right, there's actually 2 different PRs to remove any references to nested components (rather than this PR):

* `bs-modal-simple.hbs` - accesses `bs-modal/*` components
* modal header components (#693 - but I have an incoming PR for that anyway)

**Comment by simonihmig** [comment]
Ok, merged!

**Comment by lougreenwood** [comment]
thanks!

**Pull request merged**
