### PR TITLE
Yield actions in dropdown & navbar

### LINKED ISSUE #559: Yield open/close actions for DropDown

### PR DESCRIPTION
**Pull request by sdhull**
Navbar already yielded open & close actions but forcing developers to double-bookkeep the open/closed status is unnecessary when we can just yield the toggle action as well.
Dropdown is impossible to control programmatically without yielding the actions.

Fixes #559

### CODE REVIEW

**Comment by simonihmig** [comment]
@sdhull thanks for working on this! 😍

I would like to ask you to split this into two PRs if possible, so they can proceed independently. Also helps with proper Changelog generation...

Two notes in general:
* I would prefer to call the actions just like the verb, to make them consistent with the existing ones. E.g. `toggleDropdown` -> `toggle`
* I would want to have tests covering the new functionality. You should be able to find some similar ones in the codebase!

Feel free to ping me when you need help!

**Comment by sdhull** [comment]
@simonihmig yeah I initially had it as `toggle` but there's already a `toggle` component being rendered, so I wasn't sure what to do... 🤔 

Yeah I can split this into 2 PRs

**Comment by simonihmig** [comment]
@sdhull would you be able to continue work on this? I would love to get this merged.

As mentioned above, splitting this into 2 PRs, and adding some simple tests would be nice!

> yeah I initially had it as toggle but there's already a toggle component being yielded, so I wasn't sure what to do... 

Yeah, that's unfortunate. For the DropDown I would say keep it like it is now, for the NavBar maybe rename it to `toggle`, so it matches `expand` and `collapse` better.

**Comment by sdhull** [comment]
@simonihmig yeah sorry, too many things going on at once, you know how these things go. Hopefully I'll get to it this evening.

**Comment by simonihmig** [comment]
> yeah sorry, too many things going on at once, you know how these things go

Absolutely! No reason to apologize at all! 😉

**Comment by pablofrommars** [comment]
Hi,

I was about to ask how I could open and close the menu programatically and found it's a feature request. Is it planned for integration in the near future?

Thanks to everyone involved with this project!

**Comment by sdhull** [comment]
Closing in favor of #640 & #639

**Pull request closed without merging**
