### PR TITLE
Render dropdown menu in a wormhole

### LINKED ISSUE #561: Popper having trouble with parent div overflow
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
ember-bootstrap: 1.2.1 -> 1.2.1
ember-cli: ^2.18.2 -> 2.18.2
bootstrap: 4.0.0 -> 4.0.0
bootstrap-sass: n/a
ember-cli-sass: 7.1.7 -> 7.1.7
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
importBootstrapFont: false
```
**EDIT:** See end of post.

Hello,
Reporting quite a worrying bug here: if dropdown is contained inside of a div which is shorter than the container of the dropdown, the overflow is simply not shown.

calendar
Example attached. The calendar should be fully visible inside of the dropdown (and it is in case the container div is taller), but since the container div is smaller than it should, the dropdown div is cut out.
I suspect it's due to using popper instead of ember-wormhole.
Thank you,

Daniele

**Edit:**
Apparently, this bug is due to liquid-fire. I was using a `liquid-outlet` to wrap the template where I was using the dropdown, and liquid-fire probably makes use of a overflow: hidden for its features, therefore breaking ember-popper. I'll just disable liquid-fire for now.

### PR DESCRIPTION
**Pull request by simonihmig**
By setting `renderInPlace=false` to prevent clipping issues

Closes #561

### CODE REVIEW

**Comment by Techn1x** [comment]
@simonihmig Would this be possible to implement for BS3 as well? I have a container with overflow: hidden, and a dropdown inside it that gets clipped by the container. Or has the world moved on from BS3 to BS4 now

**Comment by simonihmig** [comment]
@Techn1x would probably be possible. BS3 does not do this, so the default should still be to match BS3, but an opt-in to use the same ember-popper based positioning and "wormholing" should be possible. I won't have the time for this unfortunately, but if someone wants to tackle this, I would be happy!

**Comment by bgentry** [comment]
I have discovered some menus in my app which appear to be broken by this change. Here is a menu in the top right corner of my page:

| No options specified | with `renderInPlace=false` |
| - | - |
| screen shot 2018-07-23 at 8 48 17 pm |screen shot 2018-07-23 at 8 46 24 pm |

Is that to be expected? Is there a fix necessary to either this library or ember-basic-dropdown to avoid this issue?

**Comment by simonihmig** [comment]
@bgentry are you sure this was caused by this change? The only code change was to enable changing `renderInPlace`, before it was always true (same as when not specifying it now)...

Also, on https://www.ember-bootstrap.com/#/components/dropdown, when using a narrow screen that would cause the menu to be clipped, the menu is correctly moved to the left to fit in the view:

**Comment by bgentry** [comment]
@simonihmig heh, no, clearly it couldn't have been caused by this specific change 🤦‍♂️ Sorry about that. 

Not really sure where else to look for the cause. The dropdowns in question don't have any real customization to them 🤷‍♂️

**Pull request merged**
