### PR TITLE
Remove `.btn-block` support for Bootstrap 5

### PR DESCRIPTION
**Pull request by simonihmig**
See https://getbootstrap.com/docs/5.0/migration/#buttons

### CODE REVIEW

**Review by jelhan — CHANGES_REQUESTED** [review]
I think we need to update API docs for `@block` argument as well to mention that it is not supported for BS5. Maybe an assertion throwing if the argument is used in BS5 would be also helpful.

**Comment by simonihmig** [comment]
I updated the JSDocs comment. Not sure about the assertion, like yes, would be helpful, but we have similar cases throughout the addon where we don't do this, so do we really start to do this here and not elsewhere?

**Comment by jelhan** [comment]
> I updated the JSDocs comment. Not sure about the assertion, like yes, would be helpful, but we have similar cases throughout the addon where we don't do this, so do we really start to do this here and not elsewhere?

I think a rule to add assertions to the arguments, not required by Bootstrap 5 would be helpful for migration. Do you think it would be a lot of work?

I would not care much about APIs required only for Bootstrap 3 or not supported for Bootstrap 3. The APIs either get mandatory or removed when dropping Bootstrap 3 support.

**Review by jelhan — APPROVED** [review]
I gave assertions for arguments only supported in some bootstrap versions another thought. I think you are right that we shouldn't invest time into. It will be better addressed when we have typed templates.

**Pull request merged**
