### PR TITLE
Manual include/exclude of components: <BsForm> requires <BsButton> due to yielded submitButton

### PR DESCRIPTION
**Pull request by jelhan**
Missed this in #1205

### CODE REVIEW

**Comment by jelhan** [comment]
I haven't had the time yet to verify that it actually works. I don't think we have test coverage for this feature, have we? Please review carefully.

**Comment by simonihmig** [comment]
Looks good, thank you!

> I don't think we have test coverage for this feature, have we? 

Nope :(

**Comment by simonihmig** [comment]
Released in v4.1.2

**Comment by jelhan** [comment]
Thanks a lot!

**Pull request merged**
