### PR TITLE
Fix nav link double rerender

### PR DESCRIPTION
**Pull request by simonihmig**

### CODE REVIEW

**Comment by simonihmig** [comment]
@turbo87 this should hopefully fix the problems you reported on Slack!

**Comment by Turbo87** [comment]
@simonihmig awesome, thanks!! let me know when this is released then I'll update and report back :)

**Comment by simonihmig** [comment]
@Turbo87 just had a release recently, want to get some other things fixed before releasing again. Can you try this with the master branch for now?

**Comment by Turbo87** [comment]
seems to work perfectly! thanks a lot!!

**Comment by Turbo87** [comment]
@alexspeller FYI I think you might have a similar issue in https://github.com/alexspeller/ember-cli-active-link-wrapper

**Pull request merged**
