### PR TITLE
issue #161 - let class be passed through

### PR DESCRIPTION
**Pull request by rstudner**
@simonihmig that seems to be all it took.

### CODE REVIEW

**Comment by simonihmig** [comment]
Yeah, that's basically it. But could you also add a test for it?
And apply the same to popovers?

**Comment by rstudner** [comment]
I'm trying! 

I can't run the tests locally (lots and lots of totally unrelated tests fail I do ember test).  So i'm having a hard time making sure I wrote a valid test :)

**Comment by simonihmig** [comment]
No idea why the tests should fail... I can also add them and release this, however that won't happen before tomorrow

**Comment by rstudner** [comment]
@simonihmig - Just forced pushed it back up, with 2 tests and popover added. (keep it down to 1 commit :).

**Comment by simonihmig** [comment]
Nice, thanks! 👍

**Comment by rstudner** [comment]
@simonihmig - thank you!   

And: off-topic.  I'd be up for helping with the bootstrap 4 work (I realize it is in perpetual alpha).  Having pre-made components with flexbox is becoming a necessary issue heh.

**Pull request merged**
