### PR TITLE
Remove buttonGroup value check

### PR DESCRIPTION
**Pull request by Moxide**

### CODE REVIEW

**Comment by srvance** [comment]
You beat me to it on the label! I just did a PR on this, as well.

**Comment by Moxide** [comment]
Yep just realized this ;-)
Yours is better since it deals only with this specific issue. Mine mixes two separate issues (quick and dirty)...

**Comment by simonihmig** [comment]
@Moxide Merged the other PR for this reason, hope you don't mind! ;) 

Could you rebase and fix the JSCS error that the Travis build has reported. Thanks!

**Comment by simonihmig** [comment]
Thanks!

**Comment by Moxide** [comment]
You're welcome ;-)

**Pull request merged**
