### PR TITLE
Add support for disabled property on bs-select and bs-form-element.

### LINKED ISSUE #66: Support for "disabled" property on bs-form-element

### PR DESCRIPTION
**Pull request by oswaldoacauan**
Closes #66

### CODE REVIEW

**Comment by simonihmig** [comment]
Thanks for your effort! To merge this, some component tests for the bs-form-element component would be needed however, asserting the new disabled functionality (for the different control types)!

**Comment by oswaldoacauan** [comment]
@simonihmig there is tests available on the dummy app, should i add unit tests for it?

**Comment by simonihmig** [comment]
I cannot see any automated tests anywhere? To assert the new disabled functionality you can add some simple tests to the existing component integration tests in https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-form-element-test.js.

**Comment by oswaldoacauan** [comment]
I don't see any test for other properties too. Why should disabled have tests and autofocus and placeholder not?

**Comment by offirgolan** [comment]
Hi there,

I think that if a form-element is disabled, it should also not show a [validation class](https://github.com/kaliber5/ember-bootstrap/pull/67/files#diff-87e6454240e64a006f937d01305ceebcR317).

All you would have to do is add `disabled` to the dependent keys and `|| this.get('disabled')` to the conditional block. If you guys can release this soon, that would be fantastic since we have a couple projects the need this feature. Let me know if I can help with anything to speed up the process.

**Comment by simonihmig** [comment]
@oswaldoacauan you are right about the missing tests for other properties. Must admit I was not aware of that. However trying to improve code quality over time, I would try to have all expected features to be covered by tests. I will add the missing tests for the other properties hopefully soon, can you them for `disabled`, please? If you need assistance, I surely can help!

@offirgolan Good point there! @oswaldoacauan Can you please add the logic to ignore validations for disabled elements?

**Comment by oswaldoacauan** [comment]
Closed in favor of #71 (read comments).

**Pull request closed without merging**
