### PR TITLE
.idea directory shouldn't be part of node package

### PR DESCRIPTION
**Pull request by salmanasiddiqui**

### CODE REVIEW

**Comment by simonihmig** [comment]
This is strange, `.idea` is part of `.gitignore` and as such should also be ignored by npm. Maybe it's because of the missing slash? https://github.com/kaliber5/ember-bootstrap/blob/master/.gitignore#L20

Though git seems to accept this...

**Comment by simonihmig** [comment]
Thanks anyways!

**Comment by salmanasiddiqui** [comment]
@simonihmig 
https://github.com/npm/npm/issues/3763#issuecomment-22255799

`npm` respects `.gitignore` only if there is no `.npmignore`

Welcome :wink:

**Comment by simonihmig** [comment]
Oh, did't know that, thanks for teaching me this! ;)

**Pull request merged**
