### PR TITLE
Form control plaintext

### PR DESCRIPTION
**Pull request by basz**
https://github.com/kaliber5/ember-bootstrap/issues/498

### CODE REVIEW

**Comment by basz** [comment]
first problem: BS3 apparently uses 

```
<p class="form-control-static">email@example.com</p>
```

**Comment by simonihmig** [comment]
@basz thanks for your effort so far! Let's see how to do this...

Indeed BS3 seems to expect completely different markup. That could be a reason to create a completely separate `plaintext` form control, so we create a component at `bs-form/element/control/plaintext.js` and have different implementations for BS3 and BS4 (by having separate components in the respective `bs3`/`bs4` folders).

So the API from the user's PoV would be something like `{{form.element type="plaintext" label=".." ...}}`.

Would that make sense? This would not allow for different input types in the case of BS4 (like `email`), but would that even be useful given they are `readonly` anyways?

**Comment by basz** [comment]
Ok agreed. I’ll go ahead and refactor this a bit.

Read only email tel; etc, makes sense on a implementations level but functionality wise is seems indeed a bit off.

**Comment by basz** [comment]
On second thought; who says readonly or disabled needs to be enabled for a plaintext input of types other then text?

**Comment by basz** [comment]
found that this renders (almost) what I need without EB changes


```
{{#form.element controlType="text" size='sm' readonly=true disabled=true value=(t 'table.showingOutOfTotal' this.showingOutOfTotal) as |el|}}
            {{component el.control classNames="form-control-plaintext bg-white"}}
          {{/form.element}}
```

**Comment by simonihmig** [comment]
@basz closing this as the PR seems stale and out-dated. Should you want to continue working on this, feel free to reopen! Thanks

**Pull request closed without merging**
