### PR TITLE
Test addon build with embroider

### LINKED ISSUE #915: Add Embroider test scenario

### PR DESCRIPTION
**Pull request by simonihmig**
Closes #915

Currently not working, due to some ember-prism related build failure w/ embroider. #929 would fix that...

### CODE REVIEW

**Comment by jelhan** [comment]
Not sure if I got it correctly but seems like we can't remove the dependency on `ember-cli-fastboot-testing` but at the same time we can't include it cause it brakes Embroider. If that's the case, did you tried keeping the FastBoot dependency but setting `FASTBOOT_DISABLED=true` while running the embroider test? If that doesn't work removing the FastBoot related tests from the build might be another approach? There is an example how to do it in [this Discourse topic](https://discuss.emberjs.com/t/remove-a-particular-file-folder-from-the-app-tree-depends-upon-the-build-environment/14635/2).

**Comment by simonihmig** [comment]
> Not sure if I got it correctly but seems like we can't remove the dependency on ember-cli-fastboot-testing but at the same time we can't include it cause it brakes Embroider. 

Correct.

> If that's the case, did you tried keeping the FastBoot dependency but setting FASTBOOT_DISABLED=true while running the embroider test? If that doesn't work removing the FastBoot related tests from the build might be another approach? There is an example how to do it in this Discourse topic.

Thanks for the suggestions. I just pushed a commit with a combination of those (and blacklisting ember-cli-fastboot-testing). Which solves the issue of a failing build, and most tests should pass now. With a couple of exceptions, which seem to be caused by an Embroider issue, specifically the `{{hasBlock}}` helper is somehow not working. Already investigated this, will file an issue tomorrow...

**Comment by simonihmig** [comment]
Blocked on https://github.com/embroider-build/embroider/issues/373

**Comment by simonihmig** [comment]
Rebased this, and with the latest dependencies this is passing now! :tada:
Seems the issues have been fixed upstream, through we still have to disable FastBoot due to https://github.com/embroider-build/embroider/issues/184.

**Pull request merged**
