### PR TITLE
Add input as available event for showValidationOn

### PR DESCRIPTION
**Pull request by elgordino**
I need to show validations as soon as the user presses a key so I added this action in addition to 'change' and 'focusOut'. Could you consider accepting this PR please.

Thanks!

### CODE REVIEW

**Comment by simonihmig** [comment]
Thanks for contributing!

But what is your use case here that requires `keyPress`? Wouldn't the `change` event work as well?

**Comment by elgordino** [comment]
Hi. I thought `change` would work too, but I find that it only adds the validation when the element loses focus AND the value has changed.

**Comment by simonihmig** [comment]
Yes, that's how `change` works. I see you want the validation to display immediately. But I think `input` would then be the appropriate event (http://caniuse.com/#feat=input-event).

Would you mind changing your PR to `input`?

**Comment by elgordino** [comment]
Thanks `input` is indeed more appropriate! I've updated the PR.

**Comment by simonihmig** [comment]
Thanks again!

**Pull request merged**
