### PR TITLE
Fix inline radio element used with optionLabelPath (BS3)

### PR DESCRIPTION
**Pull request by kumy**
I've not used this part, but found something that looks like an issue while exploring the code.

### CODE REVIEW

**Comment by jelhan** [comment]
Good catch! Was introduced by https://github.com/kaliber5/ember-bootstrap/commit/508ae1f3db5d044fadbf5f63dca5195541716ae2. Seems like we are missing test coverage for the combination of having an `optionLabelPath` and `inline=true`.

**Comment by jelhan** [comment]
@kumy Opened a pull request against your branch to add missing tests for this case: https://github.com/kumy/ember-bootstrap/pull/1

**Comment by simonihmig** [comment]
@jelhan thanks for putting the test together. I think I will merge this quickly, as the fix itself is fine and I wanted to cut a release today. Can you target your PR to the main repo's master instead?

**Comment by jelhan** [comment]
@simonihmig Sure. Please find it as #768.

**Pull request merged**
